(()=>{const C=MALES_CONFIG,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));let G='',K='',cart=[];
const price=s=>C.price.sizes[s];const sizes=C.defaults.sizes;
function ticker(){let x=C.ticker.map(t=>`<span>${esc(t)}</span><i>✦</i>`).join('');$('#ticker').innerHTML=x+x}
function filters(){let g=$('#gender'),c=$('#cats');g.onclick=e=>{let b=e.target.closest('button');if(!b)return;G=b.dataset.v;$$('#gender button').forEach(x=>x.classList.toggle('active',x===b));render()};c.innerHTML=`<button class="active" data-v="">Semua kategori</button>`+C.collection.categories.map(x=>`<button data-v="${x}">${x}</button>`).join('');c.onclick=e=>{let b=e.target.closest('button');if(!b)return;K=b.dataset.v;$$('#cats button').forEach(x=>x.classList.toggle('active',x===b));render()};$('#reset').onclick=()=>{G=K='';$$('#gender button,#cats button').forEach(x=>x.classList.toggle('active',!x.dataset.v));render()}}
function soon(g,k){return {id:'soon',gender:g,category:k,name:`${k} ${g}`,soon:true}}
function render(){let ps=C.products.filter(p=>(!G||p.gender===G)&&(!K||p.category===K));if(G||K){let gs=G?[G]:C.collection.genders,ks=K?[K]:C.collection.categories;gs.forEach(g=>ks.forEach(k=>{if(!C.products.some(p=>p.gender===g&&p.category===k))ps.push(soon(g,k))}))}if(!ps.length)ps=C.collection.genders.flatMap(g=>C.collection.categories.map(k=>soon(g,k)));$('#grid').innerHTML=ps.map(card).join('');$$('.product[data-id]').forEach(x=>x.onclick=()=>openProduct(x.dataset.id))}
function card(p){if(p.soon)return `<article class="product soon"><div class="pimg"><div><span>SEGERA HADIR</span><b>${esc(p.category)}</b></div></div><div class="pinfo"><small>${p.gender} · ${p.category}</small><h3>${p.name}</h3><p>Series ini sedang disiapkan oleh MALES.</p></div></article>`;return `<article class="product" data-id="${p.id}"><div class="pimg"><img src="${p.image}" class="contain" alt="${esc(p.name)}" loading="lazy"><span class="tag">${p.featured?'MALES HIGHLIGHT':'MALES SERIES'}</span><span class="quick">Lihat detail ↗</span></div><div class="pinfo"><small>${p.gender} · ${p.category} · ${p.id}</small><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="pmeta"><span>Mulai <b>${money(price('S'))}</b></span><span>${p.colors.length} warna</span></div></div></article>`}
function openProduct(id){let p=C.products.find(x=>x.id===id);if(!p)return;$('#modalContent').innerHTML=`<div class="modal-grid"><div class="modal-media"><img src="${p.image}" class="contain" alt="${esc(p.name)}"></div><div class="modal-copy"><div class="eyebrow">${p.id} / ${p.category}</div><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><div class="detail"><div><span>Bahan</span><b>${C.defaults.fabric}</b></div><div><span>Fit</span><b>${C.defaults.fit}</b></div><div><span>Logo</span><b>MALES / permanen</b></div><div><span>Warna</span><b>${p.colors.join(' · ')}</b></div></div><label class="modal-label">Pilih ukuran</label><div class="modal-sizes">${sizes.map(s=>`<button data-s="${s}"><b>${s}</b><small>${money(price(s))}</small></button>`).join('')}</div><div class="actions"><button id="add" class="btn light" disabled>Pilih ukuran terlebih dahulu</button></div></div></div>`;let chosen='';$$('.modal-sizes button').forEach(b=>b.onclick=()=>{$$('.modal-sizes button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');chosen=b.dataset.s;$('#add').disabled=false;$('#add').textContent=`Tambah ${p.name} / ${chosen} — ${money(price(chosen))}`});$('#add').onclick=()=>{cart.push({id:p.id,size:chosen});updateCart();closeModal();openBag()};$('#modal').classList.add('open');document.body.classList.add('lock')}
function closeModal(){$('#modal').classList.remove('open');document.body.classList.remove('lock')}
function updateCart(){let n=cart.length;$('#count').textContent=n;$('#items').innerHTML=n?cart.map((x,i)=>{let p=C.products.find(p=>p.id===x.id);return `<div class="item"><div><b>${p.name}</b><span>Size ${x.size} · ${money(price(x.size))}</span></div><button data-r="${i}">×</button></div>`}).join(''):`<div class="empty"><span>TAS KAMU MASIH KOSONG</span><strong>Belum ada produk yang dipilih.</strong><p>Pilih produk, tentukan ukuran, lalu kembali ke Tas sebelum checkout.</p></div>`;let t=cart.reduce((a,x)=>a+price(x.size),0);$('#total').textContent=money(t);$('#note').textContent=C.contact.whatsapp.number?'Pesanan akan dirangkum dan dikirim ke WhatsApp Admin MALES.':'Nomor WhatsApp Admin MALES belum diatur. Masukkan nomor di config.js sebelum checkout.';$$('[data-r]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.r,1);updateCart()})}
function openBag(){$('#backdrop').classList.add('open');$('#drawer').classList.add('open');document.body.classList.add('lock')}function closeBag(){$('#backdrop').classList.remove('open');$('#drawer').classList.remove('open');document.body.classList.remove('lock')}
function checkout(){if(!cart.length)return;if(!C.contact.whatsapp.number){alert('Nomor WhatsApp Admin MALES belum diatur di config.js.');return}let lines=cart.map((x,i)=>{let p=C.products.find(p=>p.id===x.id);return `${i+1}. ${p.name} — Size ${x.size} — ${money(price(x.size))}`});let t=cart.reduce((a,x)=>a+price(x.size),0);window.open(`https://wa.me/${C.contact.whatsapp.number}?text=${encodeURIComponent(C.contact.message+'\n\n'+lines.join('\n')+'\n\nTotal: '+money(t))}`,'_blank')}
function score(v,r){let m=(r[0]+r[1])/2,d=Math.max(1,(r[1]-r[0])/2);return Math.min(1,Math.abs(v-m)/(d*2))}function calc(e){e.preventDefault();let v={h:+$('#height').value,w:+$('#weight').value,c:+$('#chest').value,b:+$('#shoulder').value,p:+$('#stomach').value,sex:$('#sex').value};if(Object.values(v).some(x=>!x))return;let r=C.sizeGuide.map((x,i)=>({...x,score:score(v.h,x.h)*1.1+score(v.w,x.w)*1.25+score(v.c,x.c)*2.2+score(v.b,x.b)*(v.sex==='Wanita'?1.3:1.5)+score(v.p,x.p)*(v.sex==='Wanita'?1.9:1.7),i})).sort((a,b)=>a.score-b.score),best=r[0],next=r[1],conf=Math.max(74,Math.min(98,Math.round(100-best.score/(best.score+next.score)*22)));$('#result').innerHTML=`<div class="result-card"><div class="eyebrow">MALES FIT RESULT</div><div class="bigsize">${best.s}</div><div>${money(price(best.s))}</div><div class="confidence"><span>Kesesuaian estimasi</span><b>${conf}%</b></div><p>${conf>=90?'Profil tubuhmu cukup dekat dengan rentang ukuran ini.':'Profilmu berada di antara beberapa rentang; size ini adalah pilihan paling seimbang untuk potongan oversize.'}</p></div>`}
function sizeTable(){$('#table').innerHTML=`<div class="scroll"><table><thead><tr><th>Size</th><th>Tinggi</th><th>Berat</th><th>Dada</th><th>Bahu</th><th>Perut</th><th>Harga</th></tr></thead><tbody>${C.sizeGuide.map(x=>`<tr><td><b>${x.s}</b></td><td>${x.h.join('–')} cm</td><td>${x.w.join('–')} kg</td><td>${x.c.join('–')} cm</td><td>${x.b.join('–')} cm</td><td>${x.p.join('–')} cm</td><td>${money(price(x.s))}</td></tr>`).join('')}</tbody></table></div>`}
function init(){ticker();filters();render();sizeTable();updateCart();$('#sizeForm').onsubmit=calc;$('#bag').onclick=openBag;$('#closeBag').onclick=closeBag;$('#backdrop').onclick=closeBag;$('#checkout').onclick=checkout;$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#menu').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));$('#year').textContent=new Date().getFullYear();$('#social').innerHTML=Object.keys(C.social).map(x=>`<a href="${C.social[x]}">${x}</a>`).join('');addEventListener('scroll',()=>$('#header').classList.toggle('scrolled',scrollY>30),{passive:true})}init()})();
